monitor=,preferred,auto,auto

$terminal = ghostty
$fileManager = dolphin
$menu = rofi -show drun

source = hyprland/programs.conf
source = hyprland/autostart.conf
source = hyprland/env.conf
source = hyprland/theme.conf
source = hyprland/input.conf
source = hyprland/binds.conf
source = hyprland/windowrules.conf
