exec-once = dbus-update-activation-environment --all
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = hyprpaper
exec-once = hypridle
exec-once = waybar
exec-once = systemctl --user start hyprpolkitagent
