windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

windowrule {
    name = no-class-and-title
    no_initial_focus = true
    float = true
    move = cursor_x cursor_y
    match:class = ^$
    match:title = ^$
    match:initial_class = ^$
    match:initial_title = ^$
}

debug:disable_logs = false
debug:disable_time = false
debug:enable_stdout_logs = true
